name: py2rgt
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=2.7.*
  - cython=0.26.*
  - openssl>=1.0.2k
  - curl
  - conda-forge::readline
  - pytz
  - openblas
  - numpy=1.13.1
  - scipy=1.0
  - htslib=1.7.*
  - pysam=0.14.1
  - pybigwig=0.3.10
  - hmmlearn=20151031
  - pyx=0.12.1
  - sphinx=1.6.3
# before activating this pip install
# make sure to set the RGTDATA
# env variable via the respective
# Conda scripts

# Installation via Conda fails
# Need to run pipe install --upgrade RGT
# Something wrong with RGT requirements

#  - pip:
#      - RGT
